AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AiAlpha SAM Application - Python Lambda with API Gateway

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
        METRIC_NAMESPACE: AiAlpha

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Description: Simple Lambda to demonstrate API + metrics + structured logs
      Policies:
        - CloudWatchPutMetricPolicy: {}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"
